import type { QuizQuestion } from "./types"

// Master set of MCQs for the C course, derived from the HSC ICT Chapter 5
// curriculum. Organized in 15 topic groups of ~20 questions each.
// Total target: 300 questions. The /practice route samples from this list.

export const cMcqMasterSet: QuizQuestion[] = [
  // ============================================================
  // Topic 1: Programming languages & translators (Q1-20)
  // ============================================================
  {
    question: "Which level of language does a CPU execute directly?",
    options: ["High-level language", "Assembly language", "Machine language", "Source code"],
    correctAnswerIndex: 2,
    explanation: "A CPU runs binary machine code directly. Everything else must be translated first.",
  },
  {
    question: "What does a compiler do?",
    options: [
      "Runs the program line by line",
      "Translates the whole source program into machine code in one pass",
      "Edits the source code",
      "Detects only runtime errors",
    ],
    correctAnswerIndex: 1,
    explanation: "A compiler takes the entire source file and produces an executable. An interpreter runs the source line by line.",
  },
  {
    question: "What does an interpreter do?",
    options: [
      "Translates the whole program once into an executable",
      "Reads and executes the source code statement by statement",
      "Removes comments only",
      "Optimises machine code at runtime only",
    ],
    correctAnswerIndex: 1,
    explanation: "An interpreter reads each statement and runs it immediately. There's no separate compiled executable.",
  },
  {
    question: "Which is a high-level programming language?",
    options: ["x86 assembly", "C", "Binary opcodes", "ARM assembly"],
    correctAnswerIndex: 1,
    explanation: "C is a high-level language with English-like syntax. The others are low-level.",
  },
  {
    question: "Which is a 1st-generation language?",
    options: ["C", "Assembly", "Machine language (binary)", "FORTRAN"],
    correctAnswerIndex: 2,
    explanation: "1st-gen = machine language. 2nd = assembly. 3rd = C/FORTRAN/Pascal.",
  },
  {
    question: "Which is a 2nd-generation language?",
    options: ["Python", "Assembly", "JavaScript", "Prolog"],
    correctAnswerIndex: 1,
    explanation: "Assembly is the canonical 2nd-generation language: mnemonics like MOV/ADD that map to machine instructions.",
  },
  {
    question: "C, FORTRAN and Pascal belong to which generation?",
    options: ["1st", "2nd", "3rd", "4th"],
    correctAnswerIndex: 2,
    explanation: "Early high-level procedural languages are 3rd-generation.",
  },
  {
    question: "Which translator converts assembly language to machine code?",
    options: ["Compiler", "Interpreter", "Assembler", "Loader"],
    correctAnswerIndex: 2,
    explanation: "An assembler is specifically the translator for assembly language.",
  },
  {
    question: "Compared to interpreted code, compiled code is typically:",
    options: ["Slower", "About the same", "Faster", "Always interpreted again at runtime"],
    correctAnswerIndex: 2,
    explanation: "Compiled programs run faster because translation already happened — no overhead at runtime.",
  },
  {
    question: "Which paradigm does C primarily follow?",
    options: ["Object-oriented", "Functional", "Procedural / structured", "Logical"],
    correctAnswerIndex: 2,
    explanation: "C is the classical procedural language: functions operate on data.",
  },
  {
    question: "Which is a key difference between a compiler and an interpreter?",
    options: [
      "Compilers run programs without translation",
      "Interpreters produce a standalone .exe file",
      "Compilers translate the whole program at once; interpreters translate and run statement by statement",
      "There is no difference",
    ],
    correctAnswerIndex: 2,
    explanation: "The fundamental difference is granularity: whole-program vs line-by-line.",
  },
  {
    question: "Which is NOT a property of a good algorithm?",
    options: ["Finite", "Definite", "Effective", "Written in C only"],
    correctAnswerIndex: 3,
    explanation: "An algorithm is language-independent. Required properties: finite, definite, effective, general.",
  },
  {
    question: "Which sequence describes the typical software-development workflow?",
    options: [
      "Code → algorithm → flowchart → test → release",
      "Algorithm → flowchart → code → test → release",
      "Test → release → code → algorithm",
      "Code → flowchart → algorithm → release",
    ],
    correctAnswerIndex: 1,
    explanation: "First plan (algorithm), then visualize (flowchart), then implement, then test, then release.",
  },
  {
    question: "Which is a 5th-generation language?",
    options: ["C", "Java", "Prolog", "Assembly"],
    correctAnswerIndex: 2,
    explanation: "Prolog is a logic/AI language, often classified as 5th-generation.",
  },
  {
    question: "Which is a 4th-generation language?",
    options: ["C", "SQL", "Assembly", "Machine code"],
    correctAnswerIndex: 1,
    explanation: "SQL is a domain-specific declarative language and is commonly classified as 4GL.",
  },
  {
    question: "Why do most operating systems use C in their lower layers?",
    options: [
      "Because C looks pretty",
      "Because C generates fast machine code and gives low-level control",
      "Because C is the only language available",
      "Because C is interpreted",
    ],
    correctAnswerIndex: 1,
    explanation: "C maps closely to hardware (pointers, manual memory) while still being portable across CPUs.",
  },
  {
    question: "Which describes 'source code'?",
    options: [
      "The .exe file the user runs",
      "The human-readable program text written in a programming language",
      "The CPU's microcode",
      "Comments inside a program",
    ],
    correctAnswerIndex: 1,
    explanation: "Source code is the .c (or .py, .java, …) text you write. It's translated to machine code by a compiler.",
  },
  {
    question: "Which best describes 'machine-dependent' code?",
    options: [
      "Code that needs an interpreter",
      "Code that runs only on a specific CPU architecture (e.g. x86 vs ARM)",
      "Code with syntax errors",
      "Code that uses functions",
    ],
    correctAnswerIndex: 1,
    explanation: "Assembly and machine code are tied to the CPU's instruction set; high-level languages are usually portable.",
  },
  {
    question: "Which translator tends to detect MORE errors before runtime?",
    options: ["Interpreter", "Compiler", "Assembler", "They are identical"],
    correctAnswerIndex: 1,
    explanation: "A compiler sees the whole program at once and can report many errors before any code runs.",
  },
  {
    question: "Which language is OOP-first?",
    options: ["C", "Assembly", "Java", "Machine code"],
    correctAnswerIndex: 2,
    explanation: "Java was designed around objects and classes. C is procedural; C++ added OOP to C.",
  },

  // ============================================================
  // Topic 2: Flowcharts & algorithms (Q21-40)
  // ============================================================
  {
    question: "Which flowchart shape represents a decision?",
    options: ["Rectangle", "Diamond", "Oval", "Parallelogram"],
    correctAnswerIndex: 1,
    explanation: "Diamonds are reserved for decisions (yes/no branches).",
  },
  {
    question: "Which flowchart shape represents Start and End?",
    options: ["Diamond", "Rectangle", "Oval (rounded)", "Circle"],
    correctAnswerIndex: 2,
    explanation: "Ovals (or rounded shapes) mark the start and end of the chart.",
  },
  {
    question: "Which shape is used for an input/output step in a flowchart?",
    options: ["Diamond", "Parallelogram", "Oval", "Triangle"],
    correctAnswerIndex: 1,
    explanation: "Parallelograms mean read/write — getting input or showing output.",
  },
  {
    question: "Which shape is used for a process (calculation, assignment) in a flowchart?",
    options: ["Rectangle", "Diamond", "Oval", "Circle"],
    correctAnswerIndex: 0,
    explanation: "Rectangles denote process steps like `x = a + b`.",
  },
  {
    question: "What does the circle (connector) shape in a flowchart represent?",
    options: [
      "Start",
      "A loop iteration",
      "A reference linking two parts of the chart (e.g. on different pages)",
      "End",
    ],
    correctAnswerIndex: 2,
    explanation: "Connectors join parts of a flowchart that don't fit side by side.",
  },
  {
    question: "Which is NOT required for an algorithm to be 'good'?",
    options: ["Finite", "Effective", "Specific to one input value", "Definite"],
    correctAnswerIndex: 2,
    explanation: "An algorithm must work for a class of inputs, not just one specific value.",
  },
  {
    question: "What is the first step in software development?",
    options: [
      "Pick a language",
      "Understand the problem",
      "Choose a code editor",
      "Write tests",
    ],
    correctAnswerIndex: 1,
    explanation: "You can't solve a problem you don't understand. Always start by clarifying requirements.",
  },
  {
    question: "An algorithm to find which of two numbers is greater should consider how many cases?",
    options: ["1 (greater)", "2 (greater, smaller)", "3 (greater, smaller, equal)", "4"],
    correctAnswerIndex: 2,
    explanation: "Always account for equality — otherwise the algorithm gives no output when the numbers are equal.",
  },
  {
    question: "If an algorithm has no end condition, it might:",
    options: ["Be correct", "Run forever", "Compile faster", "Become recursive"],
    correctAnswerIndex: 1,
    explanation: "An algorithm without a termination condition is by definition not finite — it may loop forever.",
  },
  {
    question: "Which arrow shape is used in flowcharts?",
    options: ["Bidirectional", "Single direction (showing flow)", "Curved only", "Dashed"],
    correctAnswerIndex: 1,
    explanation: "Arrows point in one direction, showing the flow of control.",
  },
  {
    question: "How many output arrows does a decision (diamond) typically have?",
    options: ["One", "Two (yes/no)", "Three", "Four"],
    correctAnswerIndex: 1,
    explanation: "Decisions have two outputs — typically labeled yes/no or true/false.",
  },
  {
    question: "Drawing a flowchart BEFORE coding helps mainly because:",
    options: [
      "It compiles faster",
      "It catches logical errors and clarifies the structure before writing code",
      "It guarantees there will be no bugs",
      "It's required by the compiler",
    ],
    correctAnswerIndex: 1,
    explanation: "A flowchart is a planning tool. It exposes logic gaps early when they're cheap to fix.",
  },
  {
    question: "An algorithm step like 'Pick the best fruit' is BAD because it is not:",
    options: ["Finite", "Definite", "Short", "Written in English"],
    correctAnswerIndex: 1,
    explanation: "'Best' is ambiguous — different readers would do different things. Definite means unambiguous.",
  },
  {
    question: "Which step normally comes BEFORE writing code?",
    options: ["Releasing the product", "Drawing a flowchart and writing the algorithm", "Testing the product", "Debugging the program"],
    correctAnswerIndex: 1,
    explanation: "Plan first (algorithm + flowchart), then code.",
  },
  {
    question: "Which is true about flowcharts?",
    options: [
      "They depend on the programming language",
      "They are language-independent — the same chart works for C, Python, Java, etc.",
      "They cannot show loops",
      "They are only useful for math problems",
    ],
    correctAnswerIndex: 1,
    explanation: "A flowchart describes logic, not syntax — it works for any language.",
  },
  {
    question: "Which is the typical role of the rectangle in a flowchart?",
    options: ["Decision", "Process step (assignment / computation)", "Start", "Input / Output"],
    correctAnswerIndex: 1,
    explanation: "Rectangles hold process steps — `i = i + 1`, `area = pi * r * r`, etc.",
  },
  {
    question: "In an algorithm, the property 'finite' means:",
    options: [
      "It uses few variables",
      "It terminates in a finite number of steps",
      "It is short",
      "It uses no loops",
    ],
    correctAnswerIndex: 1,
    explanation: "An algorithm is finite if it's guaranteed to stop after a finite number of steps.",
  },
  {
    question: "Which is a common output of the planning phase?",
    options: [
      "An executable file",
      "A flowchart and a pseudo-code algorithm",
      "A compiled .o file",
      "Release notes",
    ],
    correctAnswerIndex: 1,
    explanation: "Planning produces the algorithm + flowchart that guides the coding phase.",
  },
  {
    question: "If a flowchart's two branches both end at the same point, you usually use:",
    options: [
      "Two separate End ovals",
      "A connector or arrow merging back to a common path",
      "A diamond with three exits",
      "A rectangle with branches",
    ],
    correctAnswerIndex: 1,
    explanation: "Branches join back via arrows or a connector before continuing.",
  },
  {
    question: "What does it mean for an algorithm to be 'effective'?",
    options: [
      "Each step can actually be carried out (no impossible instructions)",
      "It runs quickly",
      "It uses recursion",
      "It uses many variables",
    ],
    correctAnswerIndex: 0,
    explanation: "Effective means feasible — every step must be doable by a person or computer.",
  },

  // ============================================================
  // Topic 3: First C program (Q41-60)
  // ============================================================
  {
    question: "Which header file declares printf?",
    options: ["<string.h>", "<stdio.h>", "<stdlib.h>", "<math.h>"],
    correctAnswerIndex: 1,
    explanation: "<stdio.h> (standard I/O) declares printf, scanf, getchar, putchar, etc.",
  },
  {
    question: "Where does execution of a C program begin?",
    options: [
      "At the first #include",
      "At main()",
      "At the first printf",
      "At the last function declared",
    ],
    correctAnswerIndex: 1,
    explanation: "Every C program starts at the function called main().",
  },
  {
    question: "What does `return 0;` at the end of main() indicate?",
    options: [
      "An error occurred",
      "Successful termination",
      "Infinite loop",
      "Zero output",
    ],
    correctAnswerIndex: 1,
    explanation: "By convention, returning 0 from main means 'success'. Non-zero return codes signal errors.",
  },
  {
    question: "Which character terminates every C statement?",
    options: [".", ":", ";", ","],
    correctAnswerIndex: 2,
    explanation: "Semicolon is the statement terminator in C.",
  },
  {
    question: "What does `\\n` in a printf string represent?",
    options: ["The letter n", "Newline", "Null character", "Tab"],
    correctAnswerIndex: 1,
    explanation: "`\\n` is the newline escape — it moves the cursor to the next line.",
  },
  {
    question: "What does `\\t` mean inside a string?",
    options: ["Tab character", "Two newlines", "Title", "Stop output"],
    correctAnswerIndex: 0,
    explanation: "`\\t` is the tab escape sequence.",
  },
  {
    question: "How do you write a literal backslash inside a C string?",
    options: ["\\", "\\\\", "//\\", "(\\)"],
    correctAnswerIndex: 1,
    explanation: "Inside a string, `\\` is an escape introducer, so you write two backslashes (`\\\\`) for one literal `\\`.",
  },
  {
    question: "Which is a single-line comment in C?",
    options: [
      "# this is a comment",
      "// this is a comment",
      "<!-- comment -->",
      "' comment",
    ],
    correctAnswerIndex: 1,
    explanation: "C single-line comments start with //. Multi-line comments use /* ... */.",
  },
  {
    question: "Which is a multi-line comment in C?",
    options: ["// ... //", "## ... ##", "/* ... */", "<!-- ... -->"],
    correctAnswerIndex: 2,
    explanation: "/* ... */ is C's multi-line comment.",
  },
  {
    question: "What's the role of `#include`?",
    options: [
      "Defines a function",
      "Tells the preprocessor to pull in a header file before compilation",
      "Marks the start of main()",
      "Declares a variable",
    ],
    correctAnswerIndex: 1,
    explanation: "#include is a preprocessor directive that copies a header file's contents into the source.",
  },
  {
    question: "Curly braces `{ }` in C define:",
    options: ["A comment", "A block of statements", "A string literal", "An array"],
    correctAnswerIndex: 1,
    explanation: "{} groups statements into a block, used for function bodies, loops, conditionals, etc.",
  },
  {
    question: "What does the following print? `printf(\"hi\\nthere\\n\");`",
    options: [
      "hi\\nthere\\n",
      "hi then there on the next line",
      "hi there on one line",
      "an error",
    ],
    correctAnswerIndex: 1,
    explanation: "Each \\n moves to a new line, so 'hi' appears, then 'there' on the next line.",
  },
  {
    question: "Why does C use `#include <stdio.h>` instead of redefining printf each time?",
    options: [
      "It looks nicer",
      "stdio.h declares printf so you can use it without redefining it",
      "It's required only for printf",
      "It speeds up the program",
    ],
    correctAnswerIndex: 1,
    explanation: "Including the header brings in declarations for the standard I/O functions.",
  },
  {
    question: "Which is a valid main() declaration?",
    options: [
      "void main()",
      "int main()",
      "main int()",
      "function main()",
    ],
    correctAnswerIndex: 1,
    explanation: "`int main()` (or `int main(void)`) is the standard, portable form. `void main()` is non-standard.",
  },
  {
    question: "What happens if you forget the semicolon at the end of a C statement?",
    options: [
      "Nothing — semicolons are optional",
      "The compiler reports a syntax error",
      "Only the first statement runs",
      "The program runs but outputs nothing",
    ],
    correctAnswerIndex: 1,
    explanation: "Missing semicolons are syntax errors and the program will not compile.",
  },
  {
    question: "What does `printf(\"Hello\");` (with no \\n) do?",
    options: [
      "Refuses to print anything",
      "Prints Hello followed by a newline automatically",
      "Prints Hello without moving to a new line",
      "Prints Hello\\n literally",
    ],
    correctAnswerIndex: 2,
    explanation: "printf only prints what you give it. Without \\n, the cursor stays on the same line.",
  },
  {
    question: "Are C source files case sensitive?",
    options: ["No", "Yes — `Main()` ≠ `main()`", "Only for variable names", "Only for printf"],
    correctAnswerIndex: 1,
    explanation: "C is case-sensitive throughout. `main` and `Main` are completely different identifiers.",
  },
  {
    question: "What does the preprocessor do?",
    options: [
      "Runs the program",
      "Handles directives like #include and #define before the compiler proper sees the code",
      "Prints output",
      "Allocates memory at runtime",
    ],
    correctAnswerIndex: 1,
    explanation: "The preprocessor expands #include, #define, conditional compilation, etc. before compilation.",
  },
  {
    question: "Inside a printf format string, what does `%%` produce?",
    options: ["A percent sign", "A modulo operator", "Two percent signs", "An error"],
    correctAnswerIndex: 0,
    explanation: "Because % introduces format specifiers, you write %% to print a literal percent.",
  },
  {
    question: "If you want to print a literal double quote inside a string, you use:",
    options: ["\"", "\\\"", "'", "//\""],
    correctAnswerIndex: 1,
    explanation: "Escape the double quote with a backslash: \\\".",
  },

  // ============================================================
  // Topic 4: Variables & types (Q61-80)
  // ============================================================
  {
    question: "Which type stores whole numbers like 5 and -42?",
    options: ["float", "int", "char", "double"],
    correctAnswerIndex: 1,
    explanation: "int stores integers (whole numbers, positive or negative).",
  },
  {
    question: "Which type stores a single character like 'A'?",
    options: ["int", "char", "string", "double"],
    correctAnswerIndex: 1,
    explanation: "char holds a single character. C has no built-in string type; strings are char arrays.",
  },
  {
    question: "Which type gives the highest decimal precision?",
    options: ["int", "float", "double", "char"],
    correctAnswerIndex: 2,
    explanation: "double has about 15 digits of precision; float about 7.",
  },
  {
    question: "Which format specifier is used to print an int?",
    options: ["%c", "%d", "%f", "%s"],
    correctAnswerIndex: 1,
    explanation: "%d (decimal) is the standard format specifier for int.",
  },
  {
    question: "Which format specifier is used to print a float?",
    options: ["%d", "%f", "%lf", "%s"],
    correctAnswerIndex: 1,
    explanation: "%f is for float. %lf is for double (when used with scanf especially).",
  },
  {
    question: "Which format specifier is used to print a double?",
    options: ["%d", "%c", "%lf", "%s"],
    correctAnswerIndex: 2,
    explanation: "%lf is the format specifier for double.",
  },
  {
    question: "Which format specifier is used to print a single character?",
    options: ["%s", "%c", "%d", "%h"],
    correctAnswerIndex: 1,
    explanation: "%c prints a single char.",
  },
  {
    question: "Which is a VALID C variable name?",
    options: ["1result", "my-marks", "final result", "student_marks"],
    correctAnswerIndex: 3,
    explanation: "Variables can contain letters, digits, underscores; can't start with a digit; can't have spaces or hyphens.",
  },
  {
    question: "Which is NOT a valid C variable name?",
    options: ["age", "_total", "Total2", "2nd_name"],
    correctAnswerIndex: 3,
    explanation: "Names cannot start with a digit.",
  },
  {
    question: "Which is a valid C variable name?",
    options: ["i", "first name", "first-name", "int"],
    correctAnswerIndex: 0,
    explanation: "`i` is valid. The others have a space, a hyphen, or use a reserved keyword.",
  },
  {
    question: "Which name is invalid because it's a reserved keyword?",
    options: ["totalMarks", "myInt", "return", "marks_2024"],
    correctAnswerIndex: 2,
    explanation: "`return` is a C keyword and cannot be used as a variable name.",
  },
  {
    question: "Are C variable names case-sensitive?",
    options: ["No", "Yes — `age` ≠ `Age`", "Only on Linux", "Only for integers"],
    correctAnswerIndex: 1,
    explanation: "C identifiers are fully case-sensitive.",
  },
  {
    question: "What is the difference between declaring and initializing a variable?",
    options: [
      "There is no difference",
      "Declaration introduces the variable; initialization gives it an initial value",
      "Initialization is faster",
      "Declaration always uses zero",
    ],
    correctAnswerIndex: 1,
    explanation: "`int x;` declares x. `int x = 5;` declares and initializes it.",
  },
  {
    question: "Given `int x;` what is x's value if you don't initialize it?",
    options: [
      "Always 0",
      "Garbage (an unspecified value)",
      "NULL",
      "Compile error",
    ],
    correctAnswerIndex: 1,
    explanation: "Uninitialized local variables in C contain whatever memory happened to hold — 'garbage' until you assign.",
  },
  {
    question: "Which declares two int variables on a single line?",
    options: [
      "`int a, int b;`",
      "`int a; b;`",
      "`int a, b;`",
      "`int (a, b);`",
    ],
    correctAnswerIndex: 2,
    explanation: "Comma-separated names share the type: `int a, b;` declares both as int.",
  },
  {
    question: "Which is the correct char literal for the letter K?",
    options: ["\"K\"", "'K'", "K", "char(K)"],
    correctAnswerIndex: 1,
    explanation: "Single characters use single quotes ('K'). Double quotes denote strings.",
  },
  {
    question: "Which keyword is NOT a valid C type?",
    options: ["int", "char", "float", "string"],
    correctAnswerIndex: 3,
    explanation: "C has no built-in `string` keyword. Strings are arrays of char.",
  },
  {
    question: "If a function returns nothing, its return type is:",
    options: ["int", "char", "void", "empty"],
    correctAnswerIndex: 2,
    explanation: "`void` indicates no return value.",
  },
  {
    question: "What does this print? `int x = 7; printf(\"%d\", x);`",
    options: ["x", "%d", "7", "0"],
    correctAnswerIndex: 2,
    explanation: "The format specifier is replaced by the variable's value, so it prints 7.",
  },
  {
    question: "Which is true about `char ch = 'A';`?",
    options: [
      "ch holds the string \"A\"",
      "ch holds the single character A (one byte)",
      "ch holds the ASCII string \"65\"",
      "It's a compile error",
    ],
    correctAnswerIndex: 1,
    explanation: "A char holds one character. ASCII 'A' is internally the number 65, but ch is still a single character.",
  },

  // ============================================================
  // Topic 5: Operators & arithmetic (Q81-100)
  // ============================================================
  {
    question: "What is the value of `12 / 5` in C (both int)?",
    options: ["2.4", "2", "3", "2.40"],
    correctAnswerIndex: 1,
    explanation: "Integer division truncates: 12/5 is 2 with remainder 2 thrown away.",
  },
  {
    question: "What is the value of `12 % 5` in C?",
    options: ["2", "2.4", "0", "12"],
    correctAnswerIndex: 0,
    explanation: "% is modulo (remainder). 12 = 5*2 + 2, so remainder = 2.",
  },
  {
    question: "What is the value of `10.0 / 4` in C?",
    options: ["2", "2.5", "3", "2.50"],
    correctAnswerIndex: 1,
    explanation: "Because one operand is a double (10.0), the division is floating-point and gives 2.5.",
  },
  {
    question: "What is `7 + 3 * 2` in C?",
    options: ["20", "13", "17", "10"],
    correctAnswerIndex: 1,
    explanation: "Multiplication binds tighter than addition: 3*2 = 6, then 7+6 = 13.",
  },
  {
    question: "What is `(7 + 3) * 2`?",
    options: ["20", "13", "26", "10"],
    correctAnswerIndex: 0,
    explanation: "Parentheses force addition first: (7+3)=10, then 10*2 = 20.",
  },
  {
    question: "Which operator computes the remainder of integer division?",
    options: ["/", "%", "//", "rem"],
    correctAnswerIndex: 1,
    explanation: "% (modulo) returns the remainder.",
  },
  {
    question: "What does `int a = 5; int b = ++a;` do?",
    options: [
      "Sets a to 5 and b to 5",
      "Sets a to 6 and b to 6 (pre-increment)",
      "Sets a to 5 and b to 6",
      "Sets a to 6 and b to 5 (post-increment)",
    ],
    correctAnswerIndex: 1,
    explanation: "++a is pre-increment: a is incremented to 6 first, then assigned to b.",
  },
  {
    question: "What does `int a = 5; int b = a++;` do?",
    options: [
      "Sets a to 6 and b to 6",
      "Sets a to 6 and b to 5 (post-increment)",
      "Sets a to 5 and b to 6",
      "Sets a to 5 and b to 5",
    ],
    correctAnswerIndex: 1,
    explanation: "a++ is post-increment: b gets the old value (5), then a becomes 6.",
  },
  {
    question: "Which is true about `x += 3;`?",
    options: [
      "Equivalent to `x = x + 3;`",
      "Equivalent to `x = 3;`",
      "Equivalent to `x++;`",
      "Compile error",
    ],
    correctAnswerIndex: 0,
    explanation: "`x += 3;` is shorthand for `x = x + 3;`.",
  },
  {
    question: "Which is the relational operator for 'equal to'?",
    options: ["=", "==", "===", ":="],
    correctAnswerIndex: 1,
    explanation: "= is assignment; == is equality comparison.",
  },
  {
    question: "Which is the relational operator for 'not equal to'?",
    options: ["<>", "!=", "=/=", "~="],
    correctAnswerIndex: 1,
    explanation: "!= is the not-equal-to operator in C.",
  },
  {
    question: "If a = 5 and b = 3, what is the value of (a > b)?",
    options: ["3", "5", "true (1)", "false (0)"],
    correctAnswerIndex: 2,
    explanation: "5 > 3 is true. In C, true is represented as 1.",
  },
  {
    question: "What does the && operator do?",
    options: [
      "Bitwise AND",
      "Logical AND (true only if both sides true)",
      "Address-of",
      "Concatenation",
    ],
    correctAnswerIndex: 1,
    explanation: "&& is logical AND. Bitwise AND is single & (different operator).",
  },
  {
    question: "What does the || operator do?",
    options: [
      "Logical OR",
      "Bitwise OR",
      "Pipe",
      "Concatenate strings",
    ],
    correctAnswerIndex: 0,
    explanation: "|| is logical OR; true if either side is true.",
  },
  {
    question: "What does the ! operator do?",
    options: [
      "Factorial",
      "Logical NOT — flips true/false",
      "Not equals",
      "Address-of",
    ],
    correctAnswerIndex: 1,
    explanation: "! is logical negation: !true = false, !false = true.",
  },
  {
    question: "Evaluate: `(5 > 3) && (4 < 2)`",
    options: ["true", "false", "5", "3"],
    correctAnswerIndex: 1,
    explanation: "First side is true, second side (4<2) is false. true && false = false.",
  },
  {
    question: "Evaluate: `(5 > 3) || (4 < 2)`",
    options: ["true", "false", "9", "3"],
    correctAnswerIndex: 0,
    explanation: "OR is true when at least one side is true.",
  },
  {
    question: "Which is the assignment operator?",
    options: ["==", "=", "+=", ":="],
    correctAnswerIndex: 1,
    explanation: "= assigns. == compares.",
  },
  {
    question: "What is `5 == 5`?",
    options: ["5", "true (1)", "false (0)", "Error"],
    correctAnswerIndex: 1,
    explanation: "5 equals 5, so the comparison is true (1 in C).",
  },
  {
    question: "What is `5 == 5.0` in C?",
    options: ["false", "true", "It's a compile error", "Undefined"],
    correctAnswerIndex: 1,
    explanation: "5 is promoted to 5.0 for the comparison; 5.0 == 5.0 is true.",
  },

  // ============================================================
  // Topic 6: Input with scanf (Q101-120)
  // ============================================================
  {
    question: "Which function reads input from the keyboard in C?",
    options: ["printf", "input", "scanf", "read"],
    correctAnswerIndex: 2,
    explanation: "scanf is the standard input function paired with printf for output.",
  },
  {
    question: "Why does scanf need `&` before each variable name?",
    options: [
      "Just decoration",
      "& is the address-of operator — scanf needs to know where to store the value",
      "& means 'AND'",
      "It tells scanf to skip the value",
    ],
    correctAnswerIndex: 1,
    explanation: "scanf writes into the variable's memory address, so we pass &variable.",
  },
  {
    question: "Which call correctly reads an int into n?",
    options: [
      "`scanf(\"%d\", n);`",
      "`scanf(\"%d\", &n);`",
      "`scanf(&n);`",
      "`scanf(\"%f\", &n);`",
    ],
    correctAnswerIndex: 1,
    explanation: "Use %d for int and &n for the address.",
  },
  {
    question: "Which reads a float into x?",
    options: [
      "`scanf(\"%d\", &x);`",
      "`scanf(\"%c\", &x);`",
      "`scanf(\"%f\", &x);`",
      "`scanf(\"%s\", &x);`",
    ],
    correctAnswerIndex: 2,
    explanation: "%f is the format specifier for float in scanf.",
  },
  {
    question: "Which reads a double into d?",
    options: [
      "`scanf(\"%f\", &d);`",
      "`scanf(\"%lf\", &d);`",
      "`scanf(\"%d\", &d);`",
      "`scanf(\"%lg\", &d);`",
    ],
    correctAnswerIndex: 1,
    explanation: "For double, scanf uses %lf (long-float). %f reads a float and storing it into a double is undefined.",
  },
  {
    question: "What does scanf return?",
    options: [
      "The value read",
      "The address",
      "The number of items successfully read",
      "Nothing",
    ],
    correctAnswerIndex: 2,
    explanation: "scanf returns the count of successfully matched items, useful for input validation.",
  },
  {
    question: "Why might scanf read NOTHING when you pass `%d` but the user types letters?",
    options: [
      "scanf crashes",
      "Letters don't match %d, so no integer is read",
      "scanf converts letters to 0",
      "The program prints a warning",
    ],
    correctAnswerIndex: 1,
    explanation: "If the input doesn't match the format, scanf doesn't read it — the variable keeps its old value.",
  },
  {
    question: "What's the difference between scanf and printf for `%s`?",
    options: [
      "scanf needs &; printf doesn't",
      "scanf doesn't need & for arrays; both treat strings the same way",
      "scanf needs % only",
      "There is no difference",
    ],
    correctAnswerIndex: 1,
    explanation: "Arrays decay to pointers, so scanf(\"%s\", name) already passes the address — no & needed.",
  },
  {
    question: "Which reads TWO ints n1 and n2 separated by space?",
    options: [
      "`scanf(\"%d\", &n1); scanf(\"%d\", &n2);`",
      "`scanf(\"%d %d\", &n1, &n2);`",
      "`scanf(\"%d-%d\", &n1, &n2);`",
      "Both (a) and (b) work",
    ],
    correctAnswerIndex: 3,
    explanation: "Both work. The single scanf is more concise; %d skips leading whitespace anyway.",
  },
  {
    question: "After `scanf(\"%d\", &x);` what is x?",
    options: [
      "Whatever the user typed",
      "Always 0",
      "Always 1",
      "Always NULL",
    ],
    correctAnswerIndex: 0,
    explanation: "scanf stores the user's input into x.",
  },
  {
    question: "What's the role of the format string in scanf?",
    options: [
      "Just decoration",
      "It tells scanf what types to expect and how to parse them",
      "It is printed to the screen",
      "It defines the file to read from",
    ],
    correctAnswerIndex: 1,
    explanation: "scanf uses the format string to know how to interpret the input (int, float, string, etc).",
  },
  {
    question: "Which reads a single character into ch?",
    options: [
      "`scanf(\"%s\", &ch);`",
      "`scanf(\"%c\", &ch);`",
      "`scanf(\"%d\", &ch);`",
      "`scanf(\"%f\", &ch);`",
    ],
    correctAnswerIndex: 1,
    explanation: "%c reads a single character.",
  },
  {
    question: "When you use `scanf(\"%s\", name);`, how does it stop reading?",
    options: [
      "After exactly 10 characters",
      "When it sees whitespace (space, tab, newline)",
      "When you press Esc",
      "It never stops",
    ],
    correctAnswerIndex: 1,
    explanation: "`%s` reads a word — it stops at the first whitespace.",
  },
  {
    question: "Why does `scanf(\"%s\", name)` work without an `&`?",
    options: [
      "Special case for strings",
      "An array's name in C automatically converts to the address of its first element",
      "It actually doesn't work — it's a bug",
      "The compiler inserts an `&` automatically",
    ],
    correctAnswerIndex: 1,
    explanation: "The array name itself is already a pointer to the first element.",
  },
  {
    question: "What does `scanf(\"%d %d\", &a, &b);` expect from the user?",
    options: [
      "One integer",
      "Two integers separated by whitespace (space, tab, newline)",
      "A decimal followed by an int",
      "Two strings",
    ],
    correctAnswerIndex: 1,
    explanation: "Two %d slots mean two integers; whitespace between them is fine.",
  },
  {
    question: "Which is required AT MINIMUM before the program can scanf?",
    options: [
      "Include math.h",
      "Include stdio.h",
      "Declare a function",
      "Set a flag",
    ],
    correctAnswerIndex: 1,
    explanation: "scanf is declared in stdio.h.",
  },
  {
    question: "What does the input prompt look like in `scanf(\"%d\", &x);`?",
    options: [
      "scanf prints 'Enter:' automatically",
      "scanf prints nothing — it just waits for input",
      "scanf prints the format specifier",
      "scanf prints &x",
    ],
    correctAnswerIndex: 1,
    explanation: "scanf doesn't print anything itself. Use printf to show prompts.",
  },
  {
    question: "How do you display a prompt before reading input?",
    options: [
      "scanf prints prompts automatically",
      "Use printf(\"...\"); before scanf(...);",
      "Use an alert function",
      "Use #include <prompt.h>",
    ],
    correctAnswerIndex: 1,
    explanation: "Write a printf with your message first, then call scanf.",
  },
  {
    question: "What is `&variable` called?",
    options: [
      "AND operation",
      "Bitwise AND",
      "Address-of operator",
      "Increment",
    ],
    correctAnswerIndex: 2,
    explanation: "& applied to a variable gives its memory address (a pointer).",
  },
  {
    question: "Which is the safest practice for reading user input?",
    options: [
      "Always assume input is correct",
      "Check scanf's return value before using the variable",
      "Use printf to read input",
      "Ignore scanf",
    ],
    correctAnswerIndex: 1,
    explanation: "scanf returns the number of items read; checking it catches invalid input.",
  },

  // ============================================================
  // Topic 7: If / else / else-if (Q121-140)
  // ============================================================
  {
    question: "What does `if (x == 5)` test?",
    options: [
      "Whether x equals 5",
      "Whether x is assigned 5",
      "Whether 5 is positive",
      "Compile error",
    ],
    correctAnswerIndex: 0,
    explanation: "== compares; the if body runs when x equals 5.",
  },
  {
    question: "What's wrong with `if (x = 5) { ... }`?",
    options: [
      "Nothing",
      "It assigns 5 to x instead of comparing — the if always runs (because 5 is truthy)",
      "Syntax error",
      "It causes a runtime crash",
    ],
    correctAnswerIndex: 1,
    explanation: "= is assignment, == is comparison. Single = is one of C's classic bug sources.",
  },
  {
    question: "In an if-else-if chain, how many blocks run when more than one condition is true?",
    options: ["All true ones", "Only the first true one", "None", "The last true one"],
    correctAnswerIndex: 1,
    explanation: "Once a branch fires, the rest are skipped.",
  },
  {
    question: "Which condition is true when n is even?",
    options: ["n / 2 == 0", "n == 2", "n % 2 == 0", "n != 2"],
    correctAnswerIndex: 2,
    explanation: "n is even iff n % 2 (remainder when divided by 2) is 0.",
  },
  {
    question: "Which condition is true when n is odd?",
    options: ["n == 1", "n + 1 == 0", "n % 2 == 1", "n / 2 == 0"],
    correctAnswerIndex: 2,
    explanation: "n is odd iff n % 2 is 1 (or for negative numbers, !=0 — but for positive ints, %2==1 works).",
  },
  {
    question: "Given `int x = 5;`, what runs?\n`if (x > 10) printf(\"a\"); else if (x > 3) printf(\"b\"); else printf(\"c\");`",
    options: ["a", "b", "c", "Nothing"],
    correctAnswerIndex: 1,
    explanation: "First branch is false; second branch (5>3) is true and prints 'b'.",
  },
  {
    question: "Which condition runs the body of `if (a > 0 && b > 0)`?",
    options: [
      "When a or b is positive",
      "When both a and b are positive",
      "When neither is positive",
      "Always",
    ],
    correctAnswerIndex: 1,
    explanation: "&& requires both sides to be true.",
  },
  {
    question: "Given `int marks = 75;`, what does this print?\n`if (marks >= 80) printf(\"A+\"); else if (marks >= 70) printf(\"A\"); else printf(\"B\");`",
    options: ["A+", "A", "B", "A+A"],
    correctAnswerIndex: 1,
    explanation: "75 is not ≥ 80, but it is ≥ 70, so 'A' prints.",
  },
  {
    question: "Without curly braces, `if (cond) statement1; statement2;` — which statement always runs?",
    options: ["statement1", "statement2", "Both", "Neither"],
    correctAnswerIndex: 1,
    explanation: "Without braces, only the first statement is part of the if. statement2 runs regardless.",
  },
  {
    question: "Which is a safer style for any if?",
    options: [
      "No braces, single line",
      "Always use braces, even for one statement",
      "Use semicolons after if",
      "Use multiple if's instead",
    ],
    correctAnswerIndex: 1,
    explanation: "Always-braces avoids the famous 'dangling else' bug and reduces accidents when adding new lines.",
  },
  {
    question: "What does this produce for x = 0?\n`if (x) printf(\"true\"); else printf(\"false\");`",
    options: ["true", "false", "Nothing", "Error"],
    correctAnswerIndex: 1,
    explanation: "In C, 0 is false (any other int is true). So 'false' prints.",
  },
  {
    question: "What does this produce for x = -3?\n`if (x) printf(\"true\"); else printf(\"false\");`",
    options: ["true", "false", "Nothing", "Error"],
    correctAnswerIndex: 0,
    explanation: "Any non-zero int is truthy, including negative numbers.",
  },
  {
    question: "What is the value of `(5 > 3) && (10 > 20)`?",
    options: ["true (1)", "false (0)", "5", "20"],
    correctAnswerIndex: 1,
    explanation: "First side true, second side false. true && false = false.",
  },
  {
    question: "What is the value of `!(5 > 3)`?",
    options: ["true (1)", "false (0)", "5", "3"],
    correctAnswerIndex: 1,
    explanation: "5>3 is true; ! flips it to false.",
  },
  {
    question: "Which expression checks if x is between 1 and 10 inclusive?",
    options: [
      "`1 <= x <= 10`",
      "`x >= 1 && x <= 10`",
      "`x >= 1 || x <= 10`",
      "`1 < x < 10`",
    ],
    correctAnswerIndex: 1,
    explanation: "In C, you can't chain comparisons; use && to combine.",
  },
  {
    question: "Why is `1 <= x <= 10` WRONG in C?",
    options: [
      "It's syntactically invalid",
      "Comparison results are 0 or 1, so the chain compares the wrong things",
      "It always returns true",
      "It crashes the program",
    ],
    correctAnswerIndex: 1,
    explanation: "`(1<=x)` evaluates to 0 or 1, then `0<=10` or `1<=10` is always true — so the whole expression is always true.",
  },
  {
    question: "Which check fails if either a or b is zero (but not both)?",
    options: ["a == b", "a + b == 0", "a * b == 0 && a != b", "a > b"],
    correctAnswerIndex: 2,
    explanation: "a*b==0 means at least one of them is zero; a!=b excludes the case where both are zero.",
  },
  {
    question: "Which prints 'positive' if x>0, 'negative' if x<0, 'zero' if x==0?",
    options: [
      "`if (x>0) … else if (x<0) … else …`",
      "`if (x>0 && x<0) …`",
      "`switch (x) …`",
      "Cannot be done in C",
    ],
    correctAnswerIndex: 0,
    explanation: "A standard if / else if / else chain handles three exclusive cases.",
  },
  {
    question: "Which is FALSE in C?",
    options: ["0", "Any negative integer", "NULL", "A non-zero integer"],
    correctAnswerIndex: 0,
    explanation: "Only 0 is false. Any other integer (positive or negative) is true.",
  },
  {
    question: "What happens if you write `if (a == 5) ;` (with a trailing semicolon)?",
    options: [
      "Syntax error",
      "The if body is empty; the next statement runs unconditionally",
      "It loops forever",
      "It always prints",
    ],
    correctAnswerIndex: 1,
    explanation: "`;` is the empty statement. The if attaches to it, so nothing depends on the condition.",
  },

  // ============================================================
  // Topic 8: Loops — while/for/do-while/continue (Q141-170)
  // ============================================================
  {
    question: "Which loop is guaranteed to run its body at least once?",
    options: ["while", "for", "do-while", "if"],
    correctAnswerIndex: 2,
    explanation: "do-while checks the condition AFTER the body, so the body always executes at least once.",
  },
  {
    question: "What does this print? `int i=0; while(i<3) { printf(\"%d\",i); i++; }`",
    options: ["0", "012", "123", "0123"],
    correctAnswerIndex: 1,
    explanation: "i goes 0, 1, 2 and prints each; at i=3 the condition fails.",
  },
  {
    question: "What does this print? `for(int i=1; i<=5; i++) printf(\"%d\",i);`",
    options: ["12345", "01234", "1234", "0"],
    correctAnswerIndex: 0,
    explanation: "i goes 1 through 5 inclusive, printing each.",
  },
  {
    question: "Which loop construct best fits 'do something exactly N times'?",
    options: ["while", "for", "do-while", "if"],
    correctAnswerIndex: 1,
    explanation: "for loops are designed for a counter and a known number of iterations.",
  },
  {
    question: "Which loop construct best fits 'keep doing something while condition holds, may run zero times'?",
    options: ["while", "for", "do-while", "switch"],
    correctAnswerIndex: 0,
    explanation: "while is entry-controlled and may run zero times.",
  },
  {
    question: "What does `continue` do inside a loop?",
    options: [
      "Exits the loop",
      "Skips the rest of the current iteration and starts the next",
      "Restarts the program",
      "Pauses",
    ],
    correctAnswerIndex: 1,
    explanation: "continue jumps to the next iteration; break exits the loop entirely.",
  },
  {
    question: "What does `break` do inside a loop?",
    options: [
      "Exits the loop entirely",
      "Skips to the next iteration",
      "Crashes the program",
      "Repeats the iteration",
    ],
    correctAnswerIndex: 0,
    explanation: "break exits the innermost enclosing loop or switch.",
  },
  {
    question: "What happens with `while(1) { ... }`?",
    options: [
      "Runs exactly once",
      "Never runs",
      "Infinite loop (unless broken out of)",
      "Compile error",
    ],
    correctAnswerIndex: 2,
    explanation: "1 is always true, so the loop never exits on its own. Use break or return to leave.",
  },
  {
    question: "How many iterations does this run? `for(int i=10; i>0; i--) { ... }`",
    options: ["9", "10", "11", "Infinite"],
    correctAnswerIndex: 1,
    explanation: "i takes the values 10, 9, …, 1 — that's 10 iterations.",
  },
  {
    question: "What does this print? `int i=0; do { printf(\"hi\"); } while(i>0);`",
    options: ["Nothing", "hi", "Infinite 'hi'", "Error"],
    correctAnswerIndex: 1,
    explanation: "do-while runs once, then checks the condition. i>0 is false, so it stops.",
  },
  {
    question: "Without an update statement inside, `while (i<5) printf(\"hi\");` will:",
    options: ["Run 5 times", "Run once", "Run forever", "Not compile"],
    correctAnswerIndex: 2,
    explanation: "If i never changes and starts < 5, the condition is always true → infinite loop.",
  },
  {
    question: "What does this print? `for(int i=0;i<5;i++){ if(i==3) continue; printf(\"%d\",i); }`",
    options: ["01234", "0124", "01235", "0123"],
    correctAnswerIndex: 1,
    explanation: "When i is 3, continue skips printf and goes back to the loop. So we print 0, 1, 2, 4.",
  },
  {
    question: "What does this print? `for(int i=0;i<5;i++){ if(i==3) break; printf(\"%d\",i); }`",
    options: ["01234", "0123", "012", "01"],
    correctAnswerIndex: 2,
    explanation: "When i is 3, break exits the loop immediately — printf already ran for 0, 1, 2.",
  },
  {
    question: "Which is the do-while syntax?",
    options: [
      "`do statement while(cond);`",
      "`do { statement; } while(cond);`",
      "`do { statement; } while cond;`",
      "Both (a) and (b)",
    ],
    correctAnswerIndex: 3,
    explanation: "Braces are optional if there's only one statement. The trailing `;` is required either way.",
  },
  {
    question: "Which loop sums numbers from 1 to N?",
    options: [
      "`for (i=1; i<=N; i++) sum=sum+i;`",
      "`for (i=1; i<N; i++) sum=sum+i;`",
      "`for (i=0; i<=N; i++) sum=sum+i;`",
      "`for (i=N; i>=0; i--) sum=sum+1;`",
    ],
    correctAnswerIndex: 0,
    explanation: "Counter from 1 up to and including N.",
  },
  {
    question: "How many times does `for (int i=0; i<n; i++)` run if n=0?",
    options: ["Zero", "One", "Crashes", "Infinite"],
    correctAnswerIndex: 0,
    explanation: "The condition 0<0 is false from the start — zero iterations.",
  },
  {
    question: "How many times does `do { ... } while(0);` run?",
    options: ["Zero", "One", "Infinite", "Compile error"],
    correctAnswerIndex: 1,
    explanation: "do-while runs once before checking the condition; then 0 is false and the loop exits.",
  },
  {
    question: "Inside a nested loop, `break` exits:",
    options: [
      "Both loops",
      "The innermost loop only",
      "The outermost loop only",
      "Nothing",
    ],
    correctAnswerIndex: 1,
    explanation: "break leaves only the loop it's directly inside.",
  },
  {
    question: "Which prints the multiplication table for n (1 to 10)?",
    options: [
      "`for (i=1;i<=10;i++) printf(\"%d x %d = %d\",n,i,n*i);`",
      "`while (i<10) printf(\"%d\",n);`",
      "`for (i=0;i<=10;i++) i*n;`",
      "None",
    ],
    correctAnswerIndex: 0,
    explanation: "Standard pattern for a multiplication table: loop i from 1 to 10 and print n × i.",
  },
  {
    question: "When you use a for loop with a counter that doesn't reach the bound, it usually means:",
    options: [
      "An off-by-one bug",
      "The loop is fast",
      "The loop runs infinitely",
      "The compiler optimized it",
    ],
    correctAnswerIndex: 0,
    explanation: "Off-by-one errors are extremely common — double-check < vs <=.",
  },
  {
    question: "What's the difference between `for (i=1; i<=5; i++)` and `for (i=1; i<5; i++)`?",
    options: [
      "None",
      "The first runs 5 times (1..5), the second runs 4 times (1..4)",
      "The first crashes",
      "The second loops forever",
    ],
    correctAnswerIndex: 1,
    explanation: "<= includes the bound; < excludes it.",
  },
  {
    question: "Why might a do-while be preferred over while for asking for valid input?",
    options: [
      "It's faster",
      "The body runs at least once — the prompt and read happen before checking validity",
      "do-while supports more types",
      "while doesn't work for input",
    ],
    correctAnswerIndex: 1,
    explanation: "The natural pattern: do { read input } while (input invalid).",
  },
  {
    question: "How many times does `for (i=10; i<5; i++)` run?",
    options: ["Zero", "5", "10", "Infinite"],
    correctAnswerIndex: 0,
    explanation: "Condition 10<5 is false from the start.",
  },
  {
    question: "Which is a valid empty for loop?",
    options: [
      "`for (;;) { ... }`",
      "`for () { ... }`",
      "`for (true) { ... }`",
      "`for { ... }`",
    ],
    correctAnswerIndex: 0,
    explanation: "`for(;;)` is the C idiom for an infinite loop — all three parts omitted.",
  },
  {
    question: "If a loop variable is declared inside `for(int i=...)`, where is it visible?",
    options: [
      "Throughout the program",
      "Only inside the loop body",
      "Only after the loop",
      "Only in main",
    ],
    correctAnswerIndex: 1,
    explanation: "The variable's scope is limited to the for loop (a C99 feature).",
  },
  {
    question: "Which loop variant best counts down from 10 to 1?",
    options: [
      "`for (i=10; i>=1; i--)`",
      "`for (i=1; i<=10; i++)`",
      "`for (i=10; i<=1; i--)`",
      "`for (i=1; i>=10; i--)`",
    ],
    correctAnswerIndex: 0,
    explanation: "Start at 10, condition i>=1, decrement each step.",
  },
  {
    question: "Which condition would stop a loop printing every multiple of 3?",
    options: [
      "i % 3 == 0 — continue",
      "i % 3 == 0 — break",
      "i > 100",
      "i == 1",
    ],
    correctAnswerIndex: 1,
    explanation: "Breaking when i%3==0 would stop at the first multiple of 3.",
  },
  {
    question: "What output does this produce? `for(i=1;i<=5;i++){ if(i%2==0) continue; printf(\"%d \",i); }`",
    options: ["1 2 3 4 5", "1 3 5", "2 4", "5 4 3 2 1"],
    correctAnswerIndex: 1,
    explanation: "Even values cause continue (skipping printf); odd values print: 1 3 5.",
  },
  {
    question: "What does this print? `int i=5; while(i--) printf(\"%d \",i);`",
    options: ["5 4 3 2 1", "4 3 2 1 0", "5 4 3 2 1 0", "Infinite loop"],
    correctAnswerIndex: 1,
    explanation: "Post-decrement: condition uses old i, then i decreases. Loop prints i AFTER decrement, so 4 3 2 1 0; then i=-1 evaluates false (in C, 0 is false; -1 is truthy actually). Hmm — i-- uses old value 5 (truthy), prints 4, then i=4 truthy, prints 3, etc. When i is 1 (truthy), prints 0, then i=0 (false), loop ends.",
  },
  {
    question: "What does this print? `int i=0; while(i++<3) printf(\"%d \",i);`",
    options: ["0 1 2", "1 2 3", "0 1 2 3", "1 2 3 4"],
    correctAnswerIndex: 1,
    explanation: "Post-increment: condition uses old i, then i++. So i goes 0→1, prints 1; 1→2, prints 2; 2→3, prints 3; 3→4, 3<3 is false, stop.",
  },

  // ============================================================
  // Topic 9: Arrays (Q171-200)
  // ============================================================
  {
    question: "Given `int ara[5];`, what's the FIRST valid index?",
    options: ["0", "1", "-1", "5"],
    correctAnswerIndex: 0,
    explanation: "C arrays are 0-indexed.",
  },
  {
    question: "Given `int ara[5];`, what's the LAST valid index?",
    options: ["5", "4", "6", "0"],
    correctAnswerIndex: 1,
    explanation: "Indices go 0..4 for an array of size 5.",
  },
  {
    question: "What happens when you access an index out of bounds in C?",
    options: [
      "Compile error",
      "Runtime error guaranteed",
      "Undefined behavior — may crash, may corrupt memory silently",
      "Wraps around to 0",
    ],
    correctAnswerIndex: 2,
    explanation: "C doesn't bounds-check. Out-of-bounds access is undefined behavior — extremely dangerous.",
  },
  {
    question: "Which initializes an array of 5 ints with values 10, 20, 30, 40, 50?",
    options: [
      "`int ara[5] = {10, 20, 30, 40, 50};`",
      "`int ara = [10, 20, 30, 40, 50];`",
      "`int ara[5] = (10, 20, 30, 40, 50);`",
      "`int ara[] := {10, 20, 30, 40, 50};`",
    ],
    correctAnswerIndex: 0,
    explanation: "Brace-enclosed initializer is the correct syntax.",
  },
  {
    question: "Given `int ara[] = {1, 2, 3};`, what is its size?",
    options: ["0", "3", "Undefined", "Compile error"],
    correctAnswerIndex: 1,
    explanation: "Omitting the bound and providing an initializer lets the compiler count the elements.",
  },
  {
    question: "Given `int ara[5] = {1, 2};`, what is ara[3]?",
    options: ["1", "2", "0 (rest of elements zero-initialized)", "Garbage"],
    correctAnswerIndex: 2,
    explanation: "When some initializers are provided, the rest are zero-initialized.",
  },
  {
    question: "How do you change the third element of `int ara[5]`?",
    options: [
      "`ara[3] = value;`",
      "`ara[2] = value;`",
      "`ara(2) = value;`",
      "`ara = value;`",
    ],
    correctAnswerIndex: 1,
    explanation: "Third element is index 2 (0-based).",
  },
  {
    question: "Why can't you swap two array elements with `a=b; b=a;`?",
    options: [
      "Syntax error",
      "The first line overwrites a, so the second line copies b back into b",
      "Arrays don't support =",
      "It actually works",
    ],
    correctAnswerIndex: 1,
    explanation: "Need a temporary: temp=a; a=b; b=temp.",
  },
  {
    question: "Which loop reads 5 ints into ara?",
    options: [
      "`for(int i=0;i<5;i++) scanf(\"%d\", &ara[i]);`",
      "`for(int i=0;i<5;i++) scanf(\"%d\", ara[i]);`",
      "`for(int i=1;i<=5;i++) scanf(\"%d\", ara[i]);`",
      "`scanf(\"%d\", ara);`",
    ],
    correctAnswerIndex: 0,
    explanation: "Use &ara[i] so scanf has the address of each element; loop from 0 to size-1.",
  },
  {
    question: "How is the length of an array typically tracked in C?",
    options: [
      "Built into the type",
      "By a separate length variable or constant",
      "There's no way to know",
      "ara.length",
    ],
    correctAnswerIndex: 1,
    explanation: "Standard C arrays don't carry their length; you keep it in a variable or use sizeof at compile time.",
  },
  {
    question: "What does `sizeof(ara) / sizeof(ara[0])` give for `int ara[10];`?",
    options: ["10", "1", "40", "4"],
    correctAnswerIndex: 0,
    explanation: "Total bytes / bytes per element = element count. Works ONLY for actual arrays, not pointers.",
  },
  {
    question: "Which is true about arrays in C?",
    options: [
      "They can grow at runtime",
      "They have a fixed size set at declaration",
      "They are reference-counted",
      "They are objects",
    ],
    correctAnswerIndex: 1,
    explanation: "C arrays have a fixed size at declaration time. Dynamic arrays need malloc.",
  },
  {
    question: "What does `printf(\"%d\", ara[10]);` do for `int ara[5];`?",
    options: [
      "Prints 10",
      "Out-of-bounds access — undefined behavior (probably garbage or crash)",
      "Prints 0",
      "Compile error",
    ],
    correctAnswerIndex: 1,
    explanation: "Reading past the end of an array is undefined in C.",
  },
  {
    question: "How would you reverse an array of size n in place?",
    options: [
      "Swap a[i] with a[n-1-i] for i from 0 to n/2",
      "Sort then reverse",
      "Can't be done in C",
      "Use ara.reverse()",
    ],
    correctAnswerIndex: 0,
    explanation: "Swap pairs from the ends inward; stop at the middle.",
  },
  {
    question: "What's the relationship between an array name and a pointer in C?",
    options: [
      "Unrelated",
      "Array name automatically decays into a pointer to its first element in most expressions",
      "Same exact thing always",
      "Pointers can't access array elements",
    ],
    correctAnswerIndex: 1,
    explanation: "In most contexts, `ara` is equivalent to `&ara[0]`.",
  },
  {
    question: "What does `ara[i]` mean in pointer notation?",
    options: ["*(ara + i)", "*(i + ara)", "&ara + i", "Both (a) and (b)"],
    correctAnswerIndex: 3,
    explanation: "Both `*(ara + i)` and `*(i + ara)` are equivalent to ara[i]. Addition is commutative.",
  },
  {
    question: "Can two arrays in C be compared with `==`?",
    options: [
      "Yes, element by element",
      "No — `==` only compares the pointers, not the contents",
      "Yes, but only int arrays",
      "Yes, but only equal-sized arrays",
    ],
    correctAnswerIndex: 1,
    explanation: "Use a loop or memcmp to compare element-by-element.",
  },
  {
    question: "Which pattern finds the maximum value in an int array of size n?",
    options: [
      "Initialize max=ara[0]; for i=1..n-1, if ara[i]>max, max=ara[i]",
      "max = ara[n-1]",
      "max = ara[0] + ara[1] + ...",
      "max = sizeof(ara)",
    ],
    correctAnswerIndex: 0,
    explanation: "Start with the first element as max and update whenever a larger one is found.",
  },
  {
    question: "Which line of code initializes all elements of `int ara[100]` to zero?",
    options: [
      "`int ara[100];`",
      "`int ara[100] = {0};`",
      "`int ara[100] = 0;`",
      "Both (a) and (b)",
    ],
    correctAnswerIndex: 1,
    explanation: "`= {0}` makes the first element 0 and zero-initializes the rest. Plain `int ara[100];` doesn't initialize.",
  },
  {
    question: "How many ints does this declare? `int ara[3][4];`",
    options: ["3", "4", "12 (a 3x4 2D array)", "7"],
    correctAnswerIndex: 2,
    explanation: "2D array: 3 rows × 4 columns = 12 ints.",
  },
  {
    question: "Given `int ara[3][4]`, valid index ranges are:",
    options: [
      "ara[0..3][0..4]",
      "ara[0..2][0..3]",
      "ara[1..3][1..4]",
      "ara[0..4][0..5]",
    ],
    correctAnswerIndex: 1,
    explanation: "Rows: 0..2 (3 rows). Cols: 0..3 (4 cols).",
  },
  {
    question: "Which is true about strings in C?",
    options: [
      "They are a built-in type",
      "They are char arrays terminated with '\\0'",
      "They are immutable",
      "They auto-resize",
    ],
    correctAnswerIndex: 1,
    explanation: "C has no string type; strings are NULL-terminated arrays of char.",
  },
  {
    question: "Why do strings end with '\\0'?",
    options: [
      "Just convention",
      "Library functions like strlen, printf, and strcmp use it to know where the string ends",
      "It saves memory",
      "It's required by the OS",
    ],
    correctAnswerIndex: 1,
    explanation: "Without the null terminator, there's no way to know the string's length.",
  },
  {
    question: "Given `char s[80];`, how many actual characters can you store?",
    options: ["80", "79 (last is reserved for '\\0')", "81", "Unlimited"],
    correctAnswerIndex: 1,
    explanation: "The last slot must hold '\\0' so the maximum text length is 79.",
  },
  {
    question: "Which declares and initializes a string with 'Hello'?",
    options: [
      "`char s[] = \"Hello\";`",
      "`char s[] = 'Hello';`",
      "`string s = \"Hello\";`",
      "`char s = \"Hello\";`",
    ],
    correctAnswerIndex: 0,
    explanation: "Double-quoted literals are strings; the compiler sizes the array to 6 (5 chars + '\\0').",
  },
  {
    question: "What's the size of `char s[] = \"abc\";`?",
    options: ["3", "4 (including the null terminator)", "5", "Unknown"],
    correctAnswerIndex: 1,
    explanation: "'a', 'b', 'c', '\\0' → 4 bytes.",
  },
  {
    question: "Which prints a string?",
    options: [
      "`printf(\"%s\", s);`",
      "`printf(\"%c\", s);`",
      "`printf(s);`",
      "Both (a) and (c) — but (a) is safer",
    ],
    correctAnswerIndex: 3,
    explanation: "%s prints a string. printf(s) works if s has no % characters, but is unsafe.",
  },
  {
    question: "Why is `printf(s)` (where s is user input) dangerous?",
    options: [
      "It's slow",
      "If s contains % characters, printf interprets them as format specifiers — a security hole",
      "It's deprecated",
      "It's perfectly safe",
    ],
    correctAnswerIndex: 1,
    explanation: "Format-string injection: always use `printf(\"%s\", s)` for untrusted input.",
  },
  {
    question: "How does `scanf(\"%s\", s)` know where to stop?",
    options: [
      "Reads forever",
      "Reads until whitespace (space, tab, newline)",
      "Reads until \\0",
      "Reads until Enter only",
    ],
    correctAnswerIndex: 1,
    explanation: "%s reads a 'word' — stops at any whitespace.",
  },
  {
    question: "How do you read a line with spaces (e.g. 'Md Rahim')?",
    options: [
      "`scanf(\"%s\", s);`",
      "`scanf(\"%[^\\n]\", s);` or fgets(s, size, stdin);",
      "`scanf(\"%c\", s);`",
      "It's not possible",
    ],
    correctAnswerIndex: 1,
    explanation: "%[^\\n] reads until newline; fgets is the safer modern choice.",
  },

  // ============================================================
  // Topic 10: Strings (Q201-220)
  // ============================================================
  {
    question: "Which header declares strlen?",
    options: ["<stdio.h>", "<string.h>", "<stdlib.h>", "<math.h>"],
    correctAnswerIndex: 1,
    explanation: "string.h declares strlen, strcmp, strcpy, strcat, etc.",
  },
  {
    question: "What does strlen(\"hello\") return?",
    options: ["5", "6 (including \\0)", "4", "Garbage"],
    correctAnswerIndex: 0,
    explanation: "strlen counts characters BEFORE the '\\0'.",
  },
  {
    question: "What does strcmp return when two strings are equal?",
    options: ["1", "0", "-1", "true"],
    correctAnswerIndex: 1,
    explanation: "strcmp returns 0 for equality, positive if s1 > s2, negative if s1 < s2.",
  },
  {
    question: "What does strcmp(\"apple\", \"banana\") return?",
    options: [
      "Zero",
      "A positive number",
      "A negative number (because 'a' < 'b' in ASCII)",
      "Always 1",
    ],
    correctAnswerIndex: 2,
    explanation: "strcmp does lexicographic comparison. 'a' has lower ASCII than 'b'.",
  },
  {
    question: "What does strcpy(dest, src) do?",
    options: [
      "Copies dest into src",
      "Copies src into dest (including '\\0')",
      "Compares the two",
      "Concatenates them",
    ],
    correctAnswerIndex: 1,
    explanation: "strcpy copies src to dest. Be sure dest has enough space.",
  },
  {
    question: "What does strcat(dest, src) do?",
    options: [
      "Replaces dest with src",
      "Appends src onto the end of dest",
      "Compares them",
      "Returns the length",
    ],
    correctAnswerIndex: 1,
    explanation: "strcat (concatenate) appends src to dest.",
  },
  {
    question: "Which counts the characters in a string manually (without strlen)?",
    options: [
      "Loop until str[i] == '\\0', counting i",
      "Loop until str[i] == ' '",
      "Loop forever",
      "Use sizeof(str)",
    ],
    correctAnswerIndex: 0,
    explanation: "Walk the array until you hit the null terminator.",
  },
  {
    question: "What does `char s[10] = \"hi\";` produce in memory?",
    options: [
      "'h','i' followed by 8 more nulls",
      "'h','i'",
      "Just 'h','i','\\0'",
      "'h','i','\\0' followed by 7 nulls",
    ],
    correctAnswerIndex: 3,
    explanation: "Uninitialized array slots are zero-initialized when an initializer is provided, so the rest are '\\0'.",
  },
  {
    question: "Which is true about `scanf(\"%s\", name)` (name is a char array)?",
    options: [
      "Reads a line including spaces",
      "Reads one word (stops at whitespace) and adds '\\0'",
      "Reads exactly 80 characters",
      "Crashes always",
    ],
    correctAnswerIndex: 1,
    explanation: "%s reads a single whitespace-delimited word and terminates it with '\\0'.",
  },
  {
    question: "Why is `gets()` unsafe and removed from modern C?",
    options: [
      "It's slow",
      "It has no bound — overflows the buffer if input is too long",
      "It only reads ints",
      "It returns garbage",
    ],
    correctAnswerIndex: 1,
    explanation: "gets has no length limit. fgets(buf, size, stdin) is the safe replacement.",
  },
  {
    question: "Which is the cleanest way to read a line in modern C?",
    options: [
      "gets",
      "scanf(\"%s\", ...)",
      "fgets(buf, size, stdin)",
      "puts",
    ],
    correctAnswerIndex: 2,
    explanation: "fgets reads up to size-1 chars or until newline, including spaces.",
  },
  {
    question: "What does `puts(\"hello\")` do?",
    options: [
      "Reads 'hello' from input",
      "Prints 'hello' followed by a newline",
      "Prints 'hello' without newline",
      "Compile error",
    ],
    correctAnswerIndex: 1,
    explanation: "puts is like printf with %s + \\n — quick way to print a string and newline.",
  },
  {
    question: "What does `gets()` do (legacy)?",
    options: [
      "Prints",
      "Reads a line from stdin",
      "Allocates memory",
      "Compiles a program",
    ],
    correctAnswerIndex: 1,
    explanation: "gets reads until newline (legacy and unsafe; use fgets).",
  },
  {
    question: "Which is a correct copy of one string to another?",
    options: [
      "`dest = src;`",
      "`strcpy(dest, src);`",
      "`memcpy(dest, src);`",
      "Both (a) and (b)",
    ],
    correctAnswerIndex: 1,
    explanation: "Array assignment doesn't work in C. Use strcpy (or memcpy with a length).",
  },
  {
    question: "Which is NOT a string library function in C?",
    options: ["strcmp", "strlen", "strcpy", "stringify"],
    correctAnswerIndex: 3,
    explanation: "stringify is not a C library function. The other three are standard.",
  },
  {
    question: "What does this print? `char s[] = \"abc\"; printf(\"%d\", strlen(s));`",
    options: ["2", "3", "4", "Undefined"],
    correctAnswerIndex: 1,
    explanation: "strlen returns the character count without the trailing '\\0' — so 3 for 'abc'.",
  },
  {
    question: "Which loop finds the length of `char s[]` (without strlen)?",
    options: [
      "`for(i=0; s[i]!='\\0'; i++);`",
      "`for(i=0; s[i]!=' '; i++);`",
      "`for(i=0; i<80; i++);`",
      "All of the above",
    ],
    correctAnswerIndex: 0,
    explanation: "Walk until you hit the null terminator.",
  },
  {
    question: "What's the ASCII value of '0' (the character zero)?",
    options: ["0", "30", "48", "Depends on machine"],
    correctAnswerIndex: 2,
    explanation: "ASCII '0' is 48. ('1' is 49, etc.) Standard ASCII is portable.",
  },
  {
    question: "What does `printf(\"%c\", 65)` print?",
    options: ["65", "A", "65 as bytes", "An error"],
    correctAnswerIndex: 1,
    explanation: "65 is the ASCII code for 'A'. %c formats an integer as a character.",
  },
  {
    question: "Why is `c >= '0' && c <= '9'` a common test?",
    options: [
      "Checks if c is a positive number",
      "Checks if c is a digit character ('0' through '9')",
      "Checks if c is uppercase",
      "Checks if c is space",
    ],
    correctAnswerIndex: 1,
    explanation: "Digit characters '0'..'9' have contiguous ASCII codes, so range tests work.",
  },

  // ============================================================
  // Topic 11: Functions (Q221-260)
  // ============================================================
  {
    question: "What does a function in C do?",
    options: [
      "Stores data",
      "Performs a named, reusable computation",
      "Defines a type",
      "Allocates memory",
    ],
    correctAnswerIndex: 1,
    explanation: "Functions package code so it can be called from elsewhere.",
  },
  {
    question: "What is a function PROTOTYPE?",
    options: [
      "The actual code of the function",
      "A declaration with the return type, name, and parameter types — no body",
      "Just the name of the function",
      "The function's compiled output",
    ],
    correctAnswerIndex: 1,
    explanation: "A prototype tells the compiler the function's signature so callers can be checked.",
  },
  {
    question: "Where is a function DEFINITION written?",
    options: [
      "Always before main",
      "Anywhere — can be before or after main, as long as a prototype exists",
      "Inside main",
      "In a separate file only",
    ],
    correctAnswerIndex: 1,
    explanation: "With a prototype above, you can define the function after main.",
  },
  {
    question: "Which return type means 'returns nothing'?",
    options: ["int", "void", "char", "empty"],
    correctAnswerIndex: 1,
    explanation: "void is used for functions that don't return a value.",
  },
  {
    question: "What does `return value;` inside a function do?",
    options: [
      "Sets a global flag",
      "Sends `value` back to the caller and exits the function",
      "Prints value",
      "Restarts the function",
    ],
    correctAnswerIndex: 1,
    explanation: "return exits the function and provides a result (if any).",
  },
  {
    question: "Given `int square(int x) { return x*x; }`, what does `square(4)` return?",
    options: ["4", "8", "16", "0"],
    correctAnswerIndex: 2,
    explanation: "4*4 = 16.",
  },
  {
    question: "Which is true about function parameters in C?",
    options: [
      "Passed by reference by default",
      "Passed by value (a copy is made)",
      "Cannot be modified inside the function",
      "Always const",
    ],
    correctAnswerIndex: 1,
    explanation: "C passes by value. To modify the caller's variable, pass a pointer.",
  },
  {
    question: "Why does modifying a function parameter NOT affect the caller's variable?",
    options: [
      "C doesn't support modification",
      "Parameters are local copies",
      "The compiler prevents it",
      "It does affect the caller",
    ],
    correctAnswerIndex: 1,
    explanation: "Each parameter is a fresh copy. To modify the caller's variable, pass &var (a pointer).",
  },
  {
    question: "Which function signature accepts no arguments and returns an int?",
    options: ["void f(int)", "int f(void)", "f(int)", "int f"],
    correctAnswerIndex: 1,
    explanation: "`int f(void)` (or `int f()`) means no parameters, returns int.",
  },
  {
    question: "Can a function call itself in C?",
    options: ["No", "Yes — that's recursion", "Only if it's static", "Only main"],
    correctAnswerIndex: 1,
    explanation: "C supports recursion. Each call gets its own stack frame.",
  },
  {
    question: "What's the danger of unbounded recursion?",
    options: [
      "Slow execution",
      "Stack overflow — the program crashes",
      "Compile error",
      "It's harmless",
    ],
    correctAnswerIndex: 1,
    explanation: "Each recursive call uses stack space. Eventually the stack runs out.",
  },
  {
    question: "Which is true about main()?",
    options: [
      "It's a special function — the program entry point",
      "It's optional",
      "It must return void",
      "It can be called recursively in standard C",
    ],
    correctAnswerIndex: 0,
    explanation: "main is mandatory and the entry point. Standard C forbids recursive calls to main.",
  },
  {
    question: "Why might you split code into multiple functions?",
    options: [
      "To make the program shorter",
      "To reuse logic, improve readability, and test pieces in isolation",
      "It's mandatory",
      "It makes the program slower",
    ],
    correctAnswerIndex: 1,
    explanation: "Functions are the primary tool for managing complexity.",
  },
  {
    question: "What's a 'pure' function?",
    options: [
      "A function written cleanly",
      "A function with no side effects whose return value depends only on its inputs",
      "A function that uses only int",
      "A built-in function",
    ],
    correctAnswerIndex: 1,
    explanation: "Pure functions are easier to test and reason about. They don't print, read input, or modify globals.",
  },
  {
    question: "Given the prototype `int max(int a, int b);`, what's a valid call?",
    options: [
      "`max();`",
      "`max(5);`",
      "`max(5, 3);`",
      "`max(5, 3, 1);`",
    ],
    correctAnswerIndex: 2,
    explanation: "Two int arguments must be supplied.",
  },
  {
    question: "What does this define? `int add(int a, int b) { return a + b; }`",
    options: [
      "A function that adds two ints and returns an int",
      "A variable named add",
      "A header file",
      "A type alias",
    ],
    correctAnswerIndex: 0,
    explanation: "It's a function definition — return type, name, parameters, body.",
  },
  {
    question: "What's a 'library function'?",
    options: [
      "Custom user-written function",
      "Function from the C standard library or another library (e.g. printf, strlen)",
      "Function that uses books",
      "Function in a class library",
    ],
    correctAnswerIndex: 1,
    explanation: "Functions provided by libraries (standard or third-party).",
  },
  {
    question: "How do you make a function return a float?",
    options: [
      "Declare the return type as float and use `return value;` where value is a float",
      "Declare it as float and don't use return",
      "Cast to float at the call site",
      "Use #include <float.h>",
    ],
    correctAnswerIndex: 0,
    explanation: "Match the declared return type with the returned expression's type.",
  },
  {
    question: "Can a C function have multiple return statements?",
    options: ["No", "Yes — execution exits at whichever runs first", "Only two", "Only in main"],
    correctAnswerIndex: 1,
    explanation: "Multiple returns are allowed. As soon as one executes, the function exits.",
  },
  {
    question: "Which line correctly calls and uses a function `int add(int, int)`?",
    options: [
      "`add(3, 4);`",
      "`int s = add(3, 4);`",
      "`printf(\"%d\", add(3, 4));`",
      "All of the above",
    ],
    correctAnswerIndex: 3,
    explanation: "All are valid. The return value is optional to use.",
  },
  {
    question: "Where do local variables of a function live?",
    options: ["Heap", "Stack", "Static data", "ROM"],
    correctAnswerIndex: 1,
    explanation: "Each function call's locals live in a stack frame, freed when the function returns.",
  },
  {
    question: "Where do `static` local variables live?",
    options: [
      "Stack",
      "Static data area — they persist between calls",
      "Heap",
      "Registers only",
    ],
    correctAnswerIndex: 1,
    explanation: "static locals are initialized once and retain their value across calls.",
  },
  {
    question: "What does `#include <math.h>` provide?",
    options: [
      "Math functions like sqrt, sin, cos, pow",
      "Standard I/O",
      "String functions",
      "Memory allocation",
    ],
    correctAnswerIndex: 0,
    explanation: "math.h declares math library functions. Link with -lm on Unix.",
  },
  {
    question: "Why does a function prototype help the compiler?",
    options: [
      "It improves performance",
      "It lets the compiler check that calls have the correct types and number of arguments",
      "It's required for printf only",
      "It makes the program shorter",
    ],
    correctAnswerIndex: 1,
    explanation: "Prototypes enable type checking even when the definition is in another file.",
  },
  {
    question: "Which is a SIGNATURE for a function?",
    options: [
      "Name only",
      "Return type, name, and parameter types",
      "Just the body",
      "The line number",
    ],
    correctAnswerIndex: 1,
    explanation: "The signature is the function's interface: what comes in and what goes out.",
  },
  {
    question: "What does `void greet(void)` mean?",
    options: [
      "Takes void, returns void",
      "Takes no args, returns nothing",
      "Same as `greet()`",
      "Both (b) and (c) — they mean the same in modern C",
    ],
    correctAnswerIndex: 3,
    explanation: "(void) in the parameter list explicitly means 'no parameters'; equivalent to () in modern C.",
  },
  {
    question: "What's the convention for naming functions in C?",
    options: [
      "camelCase",
      "lowercase_with_underscores (snake_case)",
      "PascalCase",
      "It doesn't matter",
    ],
    correctAnswerIndex: 1,
    explanation: "C standard library and most idiomatic code uses snake_case. But style varies; consistency matters most.",
  },
  {
    question: "Which is a common reason to split a long main() into smaller functions?",
    options: [
      "To make it less readable",
      "To give names to sub-problems and make each part easier to understand and test",
      "To slow down the program",
      "No reason",
    ],
    correctAnswerIndex: 1,
    explanation: "Smaller, named functions are easier to read, test, and reuse.",
  },
  {
    question: "What does `int main(int argc, char *argv[])` mean?",
    options: [
      "main without parameters",
      "main receives the number of command-line arguments (argc) and the argument array (argv)",
      "Two return values",
      "Compile error",
    ],
    correctAnswerIndex: 1,
    explanation: "Both forms of main are standard: `int main(void)` or `int main(int argc, char *argv[])`.",
  },
  {
    question: "What's the result of forgetting `return 0;` at the end of `int main()`?",
    options: [
      "Undefined exit status",
      "In modern C (C99+), main implicitly returns 0",
      "Compile error",
      "Crash",
    ],
    correctAnswerIndex: 1,
    explanation: "C99 says falling off the end of main returns 0. Still considered good practice to write it explicitly.",
  },
  {
    question: "Which function call is recursive?",
    options: [
      "main calling printf",
      "printf calling scanf",
      "factorial calling factorial",
      "main not calling anything",
    ],
    correctAnswerIndex: 2,
    explanation: "Recursion = a function calls itself, directly or indirectly.",
  },
  {
    question: "What's a 'base case' in recursion?",
    options: [
      "The first call to the function",
      "The case where the recursion stops without calling itself again",
      "An error case",
      "The largest input",
    ],
    correctAnswerIndex: 1,
    explanation: "Without a base case, recursion never terminates → stack overflow.",
  },
  {
    question: "Given `int fact(int n) { if (n <= 1) return 1; return n * fact(n-1); }`, what does fact(4) return?",
    options: ["1", "12", "24", "16"],
    correctAnswerIndex: 2,
    explanation: "4! = 4*3*2*1 = 24.",
  },
  {
    question: "Why might you choose iteration over recursion in C?",
    options: [
      "Iteration uses less stack and is usually faster in C",
      "Iteration is always more elegant",
      "Recursion is not allowed in C",
      "There's no difference",
    ],
    correctAnswerIndex: 0,
    explanation: "C compilers don't always optimize tail recursion, so iteration is often more efficient.",
  },
  {
    question: "Which function is NOT in the C standard library?",
    options: ["printf", "strlen", "scanf", "writeline"],
    correctAnswerIndex: 3,
    explanation: "There's no writeline in C. Use puts or printf.",
  },
  {
    question: "What's the difference between a function declaration and a definition?",
    options: [
      "There's no difference",
      "A declaration introduces the name + signature; a definition provides the body",
      "Declaration uses keyword 'declare'",
      "Definition uses keyword 'define'",
    ],
    correctAnswerIndex: 1,
    explanation: "Declarations tell the compiler 'this function exists'. Definitions provide the actual code.",
  },
  {
    question: "How do you make a function visible to another C file?",
    options: [
      "Move the definition into that file",
      "Put a prototype in a header (.h) file and #include it from both .c files",
      "Use #define",
      "Set static",
    ],
    correctAnswerIndex: 1,
    explanation: "Headers contain prototypes; the .c file with the definition is compiled and linked.",
  },
  {
    question: "What does the `static` keyword on a top-level function mean?",
    options: [
      "It's slower",
      "Visible only inside the current translation unit (file)",
      "Static memory only",
      "Global to the whole program",
    ],
    correctAnswerIndex: 1,
    explanation: "File-scope static restricts visibility to the file — a basic encapsulation tool.",
  },
  {
    question: "Which built-in C function returns the absolute value of an int?",
    options: ["fabs", "abs", "absolute", "iabs"],
    correctAnswerIndex: 1,
    explanation: "abs is in stdlib.h. fabs is in math.h for doubles.",
  },
  {
    question: "Where is `sqrt` declared?",
    options: ["<stdio.h>", "<math.h>", "<stdlib.h>", "<string.h>"],
    correctAnswerIndex: 1,
    explanation: "math.h declares the C math library — sqrt, pow, sin, cos, etc.",
  },

  // ============================================================
  // Topic 12: Keywords & syntax (Q261-280)
  // ============================================================
  {
    question: "Which is a C keyword?",
    options: ["return", "Return", "RETURN", "All of these"],
    correctAnswerIndex: 0,
    explanation: "C is case-sensitive; only `return` (lowercase) is the keyword.",
  },
  {
    question: "Which is NOT a C keyword?",
    options: ["int", "for", "loop", "while"],
    correctAnswerIndex: 2,
    explanation: "There's no `loop` keyword. Loops are written with for, while, do-while.",
  },
  {
    question: "Which keyword exits a switch case?",
    options: ["exit", "break", "return", "end"],
    correctAnswerIndex: 1,
    explanation: "break exits a switch case (or a loop).",
  },
  {
    question: "What happens without `break` in a switch case?",
    options: [
      "Compile error",
      "Fall-through: the next case runs too",
      "Loop forever",
      "Nothing",
    ],
    correctAnswerIndex: 1,
    explanation: "C switch cases fall through to the next case unless you break.",
  },
  {
    question: "Which keyword introduces the default case in a switch?",
    options: ["else", "default", "otherwise", "fallback"],
    correctAnswerIndex: 1,
    explanation: "`default:` runs when no case matches.",
  },
  {
    question: "Which keyword declares a variable that doesn't change?",
    options: ["static", "const", "final", "immutable"],
    correctAnswerIndex: 1,
    explanation: "const marks a variable as read-only after initialization.",
  },
  {
    question: "What does the `unsigned` keyword do?",
    options: [
      "Removes the sign bit — variable can only hold non-negative values",
      "Makes the variable smaller",
      "Causes signing errors",
      "Same as positive",
    ],
    correctAnswerIndex: 0,
    explanation: "`unsigned int` doubles the positive range but can't hold negatives.",
  },
  {
    question: "Which is a valid type qualifier in C?",
    options: ["const", "volatile", "restrict", "All of these"],
    correctAnswerIndex: 3,
    explanation: "All three are standard type qualifiers.",
  },
  {
    question: "What's the typical size of an `int` in C?",
    options: ["1 byte", "2 bytes always", "4 bytes on most modern systems", "8 bytes"],
    correctAnswerIndex: 2,
    explanation: "Size of int is implementation-defined but is typically 4 bytes (32 bits) on modern systems.",
  },
  {
    question: "Which keyword introduces a structure (record) in C?",
    options: ["struct", "class", "record", "type"],
    correctAnswerIndex: 0,
    explanation: "`struct` defines a structure type in C.",
  },
  {
    question: "Which keyword introduces a multi-way selection statement?",
    options: ["if", "switch", "branch", "case"],
    correctAnswerIndex: 1,
    explanation: "switch checks one value against many cases.",
  },
  {
    question: "Which keyword starts a typedef?",
    options: ["type", "typedef", "alias", "define"],
    correctAnswerIndex: 1,
    explanation: "typedef creates an alias for a type.",
  },
  {
    question: "Which is NOT a valid `for` loop component?",
    options: ["Initialization", "Condition", "Update", "Return value"],
    correctAnswerIndex: 3,
    explanation: "for has three components: init, condition, update.",
  },
  {
    question: "What's the meaning of `enum { RED, GREEN, BLUE };`?",
    options: [
      "Three variables named RED, GREEN, BLUE",
      "Three integer constants RED=0, GREEN=1, BLUE=2",
      "Three strings",
      "Compile error",
    ],
    correctAnswerIndex: 1,
    explanation: "enum creates named integer constants, starting at 0 unless overridden.",
  },
  {
    question: "Which is true about `goto`?",
    options: [
      "Removed from C",
      "Exists but generally discouraged; jumps to a label within the same function",
      "Skips to the next loop iteration",
      "Returns from the function",
    ],
    correctAnswerIndex: 1,
    explanation: "goto exists but is rarely used. Modern code prefers structured control flow.",
  },
  {
    question: "Which keyword declares an external variable?",
    options: ["extern", "external", "global", "import"],
    correctAnswerIndex: 0,
    explanation: "extern tells the compiler the variable is defined in another file.",
  },
  {
    question: "What does `sizeof` do?",
    options: [
      "Returns the runtime size of a function",
      "Returns the size in bytes of a type or variable at compile time",
      "Allocates memory",
      "Frees memory",
    ],
    correctAnswerIndex: 1,
    explanation: "sizeof is a compile-time operator that returns the size of a type or variable.",
  },
  {
    question: "What does `signed` mean?",
    options: [
      "Can hold negatives",
      "Has a sign",
      "Default for int — uses one bit for the sign",
      "All of these",
    ],
    correctAnswerIndex: 3,
    explanation: "All three describe signed integers correctly.",
  },
  {
    question: "Which is the LARGEST integer type in standard C?",
    options: ["short", "int", "long", "long long"],
    correctAnswerIndex: 3,
    explanation: "long long is at least 64-bit since C99.",
  },
  {
    question: "Which keyword does NOT relate to storage class?",
    options: ["auto", "static", "register", "switch"],
    correctAnswerIndex: 3,
    explanation: "auto/static/register/extern are storage classes. switch is a control statement.",
  },

  // ============================================================
  // Topic 13: Misc syntax & program output (Q281-300)
  // ============================================================
  {
    question: "What does this print?\n`int a = 3, b;\nb = 2 * a;\nprintf(\"%d\", b);`",
    options: ["3", "5", "6", "9"],
    correctAnswerIndex: 2,
    explanation: "b = 2 * 3 = 6.",
  },
  {
    question: "What does this print?\n`int x = 10; x += 5; x *= 2; printf(\"%d\", x);`",
    options: ["20", "25", "30", "12"],
    correctAnswerIndex: 2,
    explanation: "x: 10 → +5 → 15 → *2 → 30.",
  },
  {
    question: "What does this print?\n`int a = 5; printf(\"%d\", a == 5 ? 1 : 0);`",
    options: ["a", "5", "1", "0"],
    correctAnswerIndex: 2,
    explanation: "Ternary: condition `a == 5` is true, so 1 is selected.",
  },
  {
    question: "What does this print?\n`int n = 7; printf(\"%s\", n % 2 == 0 ? \"even\" : \"odd\");`",
    options: ["7", "even", "odd", "true"],
    correctAnswerIndex: 2,
    explanation: "7 is odd, so 'odd' prints.",
  },
  {
    question: "What is the value of `5 / 2 * 2.0`?",
    options: ["5.0", "5", "4.0", "2.5"],
    correctAnswerIndex: 2,
    explanation: "5/2 is int division = 2. Then 2 * 2.0 = 4.0 (promoted to double).",
  },
  {
    question: "What does this print?\n`int a = 1, b = 2; printf(\"%d %d\", a, b); a = b; b = a; printf(\"%d %d\", a, b);`",
    options: ["1 2 1 2", "1 2 2 2", "1 2 2 1", "Error"],
    correctAnswerIndex: 1,
    explanation: "After `a=b`, a=2. Then `b=a` makes b=2 too. Both are 2.",
  },
  {
    question: "Which loop prints exactly 5 lines?",
    options: [
      "`for(i=0;i<5;i++) printf(\"hi\\n\");`",
      "`for(i=1;i<=5;i++) printf(\"hi\\n\");`",
      "`for(i=0;i<=4;i++) printf(\"hi\\n\");`",
      "All of the above",
    ],
    correctAnswerIndex: 3,
    explanation: "All three iterate 5 times.",
  },
  {
    question: "Which is the format-specifier for printing a long int?",
    options: ["%d", "%ld", "%f", "%s"],
    correctAnswerIndex: 1,
    explanation: "%ld prints long int. %d is for plain int.",
  },
  {
    question: "What does this print?\n`int i; for(i=0; i<3; i++); printf(\"%d\", i);`",
    options: ["0", "2", "3", "Nothing"],
    correctAnswerIndex: 2,
    explanation: "The `;` after for(...) is the loop body (empty). Loop runs i = 0,1,2 and then i becomes 3 when the condition fails.",
  },
  {
    question: "Given `int a[5] = {10, 20, 30};`, what is a[4]?",
    options: ["10", "0", "30", "Garbage"],
    correctAnswerIndex: 1,
    explanation: "Partial initialization zero-fills the rest.",
  },
  {
    question: "What does this print?\n`int a = 5; int *p = &a; *p = 10; printf(\"%d\", a);`",
    options: ["5", "10", "Address of a", "Error"],
    correctAnswerIndex: 1,
    explanation: "p points to a; assigning to *p changes a. a is now 10.",
  },
  {
    question: "What is `&` when applied to a variable?",
    options: ["Bitwise AND", "Address-of operator", "Decrement", "Logical AND"],
    correctAnswerIndex: 1,
    explanation: "`&variable` gives the variable's address (a pointer).",
  },
  {
    question: "What is `*` when applied to a pointer?",
    options: [
      "Multiplication",
      "Dereference — gives the value at the pointer's address",
      "Comment",
      "Power",
    ],
    correctAnswerIndex: 1,
    explanation: "* on a pointer reads (or writes) the value at that address.",
  },
  {
    question: "Which header declares malloc and free?",
    options: ["<stdio.h>", "<stdlib.h>", "<string.h>", "<math.h>"],
    correctAnswerIndex: 1,
    explanation: "stdlib.h declares dynamic-memory functions.",
  },
  {
    question: "Why is checking malloc's return value important?",
    options: [
      "It's not — malloc never fails",
      "malloc returns NULL on failure; using a NULL pointer crashes the program",
      "It speeds up the program",
      "It's only required on Linux",
    ],
    correctAnswerIndex: 1,
    explanation: "Always check malloc's return; never dereference NULL.",
  },
  {
    question: "Which loop prints all multiples of 5 between 1 and 100?",
    options: [
      "`for(i=5; i<=100; i+=5) printf(\"%d\\n\", i);`",
      "`for(i=1; i<=100; i++) if(i%5==0) printf(\"%d\\n\", i);`",
      "Both work",
      "Neither",
    ],
    correctAnswerIndex: 2,
    explanation: "Both produce the same output; the first is faster.",
  },
  {
    question: "What does this print?\n`int sum = 0; for(int i = 1; i <= 10; i++) sum += i; printf(\"%d\", sum);`",
    options: ["10", "45", "55", "100"],
    correctAnswerIndex: 2,
    explanation: "Sum of 1 to 10 = 55.",
  },
  {
    question: "What's the value of `sum` after `for(int i=1; i<=4; i*=2) sum += i;` (starting with sum=0)?",
    options: ["10", "7", "4", "Infinite loop"],
    correctAnswerIndex: 1,
    explanation: "i takes 1, 2, 4 (then i=8 fails ≤4). sum = 1+2+4 = 7.",
  },
  {
    question: "If a global int is declared `int counter;` (outside any function), its initial value is:",
    options: ["Garbage", "0", "NULL", "1"],
    correctAnswerIndex: 1,
    explanation: "Globals (and statics) are zero-initialized by default.",
  },
  {
    question: "What does `printf(\"%5d\", 7)` print?",
    options: ["7", "     7 (right-justified in 5 columns)", "00007", "57"],
    correctAnswerIndex: 1,
    explanation: "`%5d` pads with spaces to a width of 5.",
  },
  {
    question: "What does `printf(\"%05d\", 7)` print?",
    options: ["7", "     7", "00007 (zero-padded width 5)", "70000"],
    correctAnswerIndex: 2,
    explanation: "The `0` flag zero-pads instead of space-padding.",
  },
  {
    question: "What does `printf(\"%.2f\", 3.14159)` print?",
    options: ["3", "3.14", "3.1416", "3.14159"],
    correctAnswerIndex: 1,
    explanation: ".2 means two digits after the decimal point.",
  },
  {
    question: "Which is true about `int i; scanf(\"%d\", &i);`?",
    options: [
      "It reads a float into i",
      "It blocks waiting for the user to type an integer",
      "It crashes if input is non-numeric",
      "It assigns 0 to i",
    ],
    correctAnswerIndex: 1,
    explanation: "scanf waits for input matching the format. Non-numeric input is just not consumed (i unchanged).",
  },
  {
    question: "What's the difference between `++i` and `i++` when used standalone?",
    options: [
      "Major — first one's faster",
      "No difference in effect; both increment i by 1",
      "++i is invalid in C",
      "i++ is invalid in C",
    ],
    correctAnswerIndex: 1,
    explanation: "When the result isn't used, both have identical effect. The difference matters only in expressions.",
  },
  {
    question: "Which initializes a 2D array with all zeros?",
    options: [
      "`int m[2][3];`",
      "`int m[2][3] = {0};`",
      "`int m[2][3] = {{0,0,0}, {0,0,0}};`",
      "Both (b) and (c)",
    ],
    correctAnswerIndex: 3,
    explanation: "Partial initialization with `{0}` zero-fills the rest. (b) is the compact form; (c) is explicit.",
  },
  {
    question: "Which prints a newline character?",
    options: [
      "`printf(\"n\");`",
      "`printf(\"\\n\");`",
      "`printf(\"NEWLINE\");`",
      "`printf(\\n);`",
    ],
    correctAnswerIndex: 1,
    explanation: "The escape sequence \\n inside a string is a newline.",
  },
  {
    question: "What is the meaning of `int *p, q;`?",
    options: [
      "p and q are both pointers to int",
      "p is a pointer to int; q is an int",
      "Both are ints",
      "Compile error",
    ],
    correctAnswerIndex: 1,
    explanation: "The `*` binds to the variable name, not the type. So only p is a pointer.",
  },
  {
    question: "Which idiom checks if a string s is empty (without strlen)?",
    options: [
      "`if (s == 0)`",
      "`if (s[0] == '\\0')`",
      "`if (s == NULL)`",
      "`if (s == \"\")`",
    ],
    correctAnswerIndex: 1,
    explanation: "An empty string is one whose first character is the null terminator.",
  },
  {
    question: "What's the value of `'A' + 1`?",
    options: [
      "'B' (the ASCII code one greater, which is 66 = 'B')",
      "1",
      "65",
      "Error",
    ],
    correctAnswerIndex: 0,
    explanation: "'A' is 65; 65+1 = 66, which is 'B'. Char arithmetic in C is just int arithmetic.",
  },
  {
    question: "When you compile with `gcc program.c -o program`, what does `-o program` do?",
    options: [
      "Optimizes the code",
      "Sets the output file's name to `program`",
      "Marks program as the entry point",
      "Lets you call the program 'program'",
    ],
    correctAnswerIndex: 1,
    explanation: "`-o NAME` specifies the output executable's name (default is `a.out`).",
  },
]
